import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import TextArea from "@/components/Base/TextArea";
import Profile from "@/pages/profile";
import EventInfo from "@/components/FAQ-modal/EventInfo";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>OCAQ' 24</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
      		<TextArea>
				<EventInfo />
      		</TextArea>
		</>
	);
}
